### PR TITLE
Remove option to specify environment URL from the UI

### PR DESCRIPTION
**Pull request by jaguilar-atl**

### CODE REVIEW

**Review by dkjellin — APPROVED** [review]

**Comment by KalleOlaviNiemitalo** [comment]
Why was this removed? I don't see any comments about that in <https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/pull/296>, either.

**Comment by KalleOlaviNiemitalo** [comment]
`src/main/resources/com/atlassian/bitbucket/jenkins/internal/deployments/DeploymentNotifier/help-environmentUrl.html` seems a bit orphaned now.

**Comment by khughes-atlassian** [comment]
> Why was this removed? I don't see any comments about that in #296, either.

The environment URL isn't being used in Bitbucket Server yet. The API accepts it and stores it in the DB, but the UI doesn't use it at all. Users were a bit confused about it during testing so we decided that it is better for us to not show the field until it is actually useful. We haven't changed the the deployment pipeline step, so it will still allow the environment URL to be used there if people do have a compelling reason to send it to Bitbucket Server.

**Comment by jaguilar-atl** [comment]
> `...DeploymentNotifier/help-environmentUrl.html` seems a bit orphaned now
Thanks @KalleOlaviNiemitalo. I'll push a separate PR up to remove this as well.

**Comment by maestropastelero** [comment]
Guys

Regarding environmentURL parameter,  I don't see this in the bitbucket Rest documentation, but in my company we do use this call below in the Pipeline and it does update de URL on the bitbucket PR with the URL information.

Maybe you can add something like that in bbs_deploy(), I would love to use bbs_deploy instead of updating with curl on each step of my Pipeline.
We are using: Atlassian Bitbucket v8.17.0

curl --request POST --url https://[bitbucket_URL]/rest/api/latest/projects/[PROJECT NAME]/repos/[REPO]/commits/[COMMIT ID]/deployments \
                      -H 'Accept: application/json' \
                      -H "Content-Type: application/json" \
                      -H "X-Atlassian-Token: no-check" \
                      --user '${JENKINS_SVC}' \
                      --data '{"description": "Some description", "key": "My-Key","state": "SUCCESSFUL","displayName": "Build number","deploymentSequenceNumber": 1,"environment": {  "key": "My-Key",  "type": "DEVELOPMENT",  "displayName": "some name ",  "url": "https://myenv-pr-${PR_NUMBER}.company.com/"},  "url": "https://myenv-pr-${PR_NUMBER}.company.com/"}'

**Pull request merged**
