### PR TITLE
Credentials upgrade and Jenkins version bump

### PR DESCRIPTION
**Pull request by mhenschke-atl**

### CODE REVIEW

**Review by dkjellin — COMMENTED** [review]
I think you also need to update the `Readme` with the change in Jenkins version and add an entry to the change log.

You also have a compilation error that needs to be fixed before we merge :D

**Comment by KalleOlaviNiemitalo** [comment]
Have you considered using [Bill of Materials for Jenkins plugins](https://github.com/jenkinsci/bom)?

**Comment by mhenschke-atl** [comment]
> I think you also need to update the `Readme` with the change in Jenkins version and add an entry to the change log.
> 
> You also have a compilation error that needs to be fixed before we merge :D

That's what I get for making blind changes... Fixed, cheers

**Review by dkjellin — APPROVED** [review]

**Comment by dkjellin** [comment]
@mhenschke-atl I think this PR is now stale and can be closed?

**Pull request closed without merging**
