### PR TITLE
Feature: Deployment status

### PR DESCRIPTION
**Pull request by khughes-atlassian**
Adds integration with Bitbucket Data Center's [deployment status API](https://docs.atlassian.com/bitbucket-server/rest/7.17.0/bitbucket-rest.html#idp241) that was released in version 7.16.0

For Freestyle jobs, this is implemented as a post-build action. The action will post an in-progress notification of the deployment during the Bitbucket SCM checkout, and a final notification during the post-build stage.
Screen Shot 2021-10-25 at 11 27 15 am

For Pipeline and Multibranch Pipeline jobs, this is implemented as a wrapper step. The `bbs_deploy` step will post an in-progress notification to Bitbucket DC at the start of the block, and a final status at the end of the block based on whether the steps within the block were successful or not.
Screen Shot 2021-10-25 at 11 29 30 am

```groovy
bbs_deploy(environmentKey: '47f1081b-899f-42c5-b0ad-4778ca664b34', environmentName: 'My Production Environment', environmentType: 'PRODUCTION', environmentUrl: 'http://url.to.prod') {
    // some block
}
```

The `environmentKey` and `environmentName` fields are required. You can use the syntax generator to generate an `environmentKey`, or you can use something more readable as long as it is unique across all environments used by the repository.

### CODE REVIEW

**Review by dkjellin — APPROVED** [review]
I think this looks good, I did not review the tests in detail, but given this is a PR of already reviewed PRs I figure that was ok. 

Thee things are left to do
1. Update the pom.xml to have version 3.1.0-SNAPSHOT
2. Update the readme release notes with details of the deployments feature 
3. Update the documentation on how to use the deployments feature

All three of them can be done in a different PR to this, as long as it is done before the release is cut.

**Comment by jaguilar-atl** [comment]
Thanks @dkjellin! I'll merge this now and will create a separate PR to address those remaining tasks.

**Comment by jaguilar-atl** [comment]
Thanks @dkjellin! I'll merge this PR now and will create a separate PR for the remaining required tasks.

**Comment by maestropastelero** [comment]
> Adds integration with Bitbucket Data Center's [deployment status API](https://docs.atlassian.com/bitbucket-server/rest/7.17.0/bitbucket-rest.html#idp241) that was released in version 7.16.0
> 
> For Freestyle jobs, this is implemented as a post-build action. The action will post an in-progress notification of the deployment during the Bitbucket SCM checkout, and a final notification during the post-build stage. Screen Shot 2021-10-25 at 11 27 15 am
> 
> For Pipeline and Multibranch Pipeline jobs, this is implemented as a wrapper step. The `bbs_deploy` step will post an in-progress notification to Bitbucket DC at the start of the block, and a final status at the end of the block based on whether the steps within the block were successful or not. Screen Shot 2021-10-25 at 11 29 30 am
> 
> ```groovy
> bbs_deploy(environmentKey: '47f1081b-899f-42c5-b0ad-4778ca664b34', environmentName: 'My Production Environment', environmentType: 'PRODUCTION', environmentUrl: 'http://url.to.prod') {
>     // some block
> }
> ```
> 
> The `environmentKey` and `environmentName` fields are required. You can use the syntax generator to generate an `environmentKey`, or you can use something more readable as long as it is unique across all environments used by the repository.

@khughes-atlassian , I'd tried so many different setup and none of them have the environmentUrl option you showed on that image. If I added it manually as a bbs_deploy option it does nothing.

Any idea what could be missing?, I do get the job status correctly on the bitbucket side while deploying

**Pull request merged**
